name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      # Runs whatever you configured in .pre-commit-config.yaml (black, flake8, etc.)
      - name: Run pre-commit (format + lint)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Run tests with coverage
        env:
          PYTEST_ADDOPTS: ""   # nuke any injected flags from env/Actions variables
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          python - << "PY"
import os, pkgutil, pytest
print("PYTEST_ADDOPTS:", repr(os.environ.get("PYTEST_ADDOPTS")))
print("pytest version:", pytest.__version__)
print("pytest-cov present:", any(m.name=="pytest_cov" for m in pkgutil.iter_modules()))
PY
          python -m pytest -p pytest_cov --cov=job_link_logger --cov-report=term-missing -q



